name: jol_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.9.1
  material_design_icons_flutter: ^7.0.7296
  google_fonts: ^6.3.0
  get: ^4.7.2
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4   # ðŸ‘ˆ moved here (correct place)

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: Digitalt
      fonts:
        - asset: lib/assets/fonts/Digitalt.ttf
    - family: Aleo
      fonts:
        - asset: lib/assets/fonts/Aleo.ttf

# ðŸ‘‡ Launcher icon config
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/logo.png"
  min_sdk_android: 21
